### PR TITLE
use scala-dev Travis-CI include

### PR DESCRIPTION
**Pull request by SethTisue**

### CODE REVIEW

**Comment by SethTisue** [comment]
@eed3si9n what do you make of the failure here — looks like an SDKMAN problem?

**Comment by eed3si9n** [comment]
JDK 14? I have no idea if it's SDKMAN, Travis CI, or sbt.

**Comment by SethTisue** [comment]
ah, it's this line in `travis/default.yml`:

```
  java -version 2>&1 | grep "^.*AdoptOpenJDK[^0-9]*$versionPrefix\..*$" || exit 1
```

I'll push an adjustment

**Comment by SethTisue** [comment]
I think scala/scala-dev@ac09af54f48fae0391bd0bd178597b6478356247 fixes it, but now Travis-CI is down, LOL

**Comment by SethTisue** [comment]
now it's not erroring, but it also doesn't work. https://travis-ci.org/github/SethTisue/Project-Euler/jobs/665115734 requests 14 but gets 11

**Comment by SethTisue** [comment]
https://github.com/scala/scala-dev/issues/704

**Comment by SethTisue** [comment]
false alarm, it is in fact getting 14

**Pull request merged**
